import { getMatchIdsForRound, type RoundKey } from '../engine/rounds'
import {
  type PredictionRoundKey,
  PREDICTION_ROUND_RANGES,
} from '../constants'

export interface ScheduleEntry {
  kickoffUtc: string // ISO 8601 UTC
  venue: string
}

/**
 * Official FIFA World Cup 2026 match schedule.
 * Sources: FIFA, NBC Sports, Sky Sports, Fox Sports (cross-referenced).
 *
 * Match IDs 1-72: group stage (generated by lib/data/fixtures.ts).
 * Match IDs 73-104: knockout stage (bracket-template.ts).
 *
 * Groups B, F, I, K were reordered in groups.ts so our MD1/MD2/MD3
 * match pairings align with FIFA's actual matchday assignments.
 */
export const schedule: Record<number, ScheduleEntry> = {
  // ── Group A  [MEX, ZAF, KOR, CZE] ────────────────────────────
  // MD1
  1:  { kickoffUtc: '2026-06-11T19:00:00Z', venue: 'Estadio Azteca, Mexico City' },
  2:  { kickoffUtc: '2026-06-12T02:00:00Z', venue: 'Estadio Akron, Guadalajara' },
  // MD2
  3:  { kickoffUtc: '2026-06-19T01:00:00Z', venue: 'Estadio Akron, Guadalajara' },
  4:  { kickoffUtc: '2026-06-18T16:00:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },
  // MD3
  5:  { kickoffUtc: '2026-06-25T01:00:00Z', venue: 'Estadio Azteca, Mexico City' },
  6:  { kickoffUtc: '2026-06-25T01:00:00Z', venue: 'Estadio BBVA, Monterrey' },

  // ── Group B  [CAN, BIH, QAT, CHE] ────────────────────────────
  // MD1
  7:  { kickoffUtc: '2026-06-12T19:00:00Z', venue: 'BMO Field, Toronto' },
  8:  { kickoffUtc: '2026-06-13T19:00:00Z', venue: "Levi's Stadium, Santa Clara" },
  // MD2
  9:  { kickoffUtc: '2026-06-18T22:00:00Z', venue: 'BC Place, Vancouver' },
  10: { kickoffUtc: '2026-06-18T19:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  // MD3
  11: { kickoffUtc: '2026-06-24T19:00:00Z', venue: 'BC Place, Vancouver' },
  12: { kickoffUtc: '2026-06-24T19:00:00Z', venue: 'Lumen Field, Seattle' },

  // ── Group C  [BRA, MAR, HTI, SCO] ────────────────────────────
  // MD1
  13: { kickoffUtc: '2026-06-13T22:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
  14: { kickoffUtc: '2026-06-14T01:00:00Z', venue: 'Gillette Stadium, Foxborough' },
  // MD2
  15: { kickoffUtc: '2026-06-20T01:00:00Z', venue: 'Lincoln Financial Field, Philadelphia' },
  16: { kickoffUtc: '2026-06-19T22:00:00Z', venue: 'Gillette Stadium, Foxborough' },
  // MD3
  17: { kickoffUtc: '2026-06-24T22:00:00Z', venue: 'Hard Rock Stadium, Miami' },
  18: { kickoffUtc: '2026-06-24T22:00:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },

  // ── Group D  [USA, PRY, AUS, TUR] ────────────────────────────
  // MD1
  19: { kickoffUtc: '2026-06-13T01:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  20: { kickoffUtc: '2026-06-14T04:00:00Z', venue: 'BC Place, Vancouver' },
  // MD2
  21: { kickoffUtc: '2026-06-19T19:00:00Z', venue: 'Lumen Field, Seattle' },
  22: { kickoffUtc: '2026-06-20T04:00:00Z', venue: "Levi's Stadium, Santa Clara" },
  // MD3
  23: { kickoffUtc: '2026-06-26T02:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  24: { kickoffUtc: '2026-06-26T02:00:00Z', venue: "Levi's Stadium, Santa Clara" },

  // ── Group E  [DEU, CUW, CIV, ECU] ────────────────────────────
  // MD1
  25: { kickoffUtc: '2026-06-14T17:00:00Z', venue: 'NRG Stadium, Houston' },
  26: { kickoffUtc: '2026-06-14T23:00:00Z', venue: 'Lincoln Financial Field, Philadelphia' },
  // MD2
  27: { kickoffUtc: '2026-06-20T20:00:00Z', venue: 'BMO Field, Toronto' },
  28: { kickoffUtc: '2026-06-21T00:00:00Z', venue: 'Arrowhead Stadium, Kansas City' },
  // MD3
  29: { kickoffUtc: '2026-06-25T20:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
  30: { kickoffUtc: '2026-06-25T20:00:00Z', venue: 'Lincoln Financial Field, Philadelphia' },

  // ── Group F  [NLD, JPN, SWE, TUN] ────────────────────────────
  // MD1
  31: { kickoffUtc: '2026-06-14T20:00:00Z', venue: 'AT&T Stadium, Dallas' },
  32: { kickoffUtc: '2026-06-15T02:00:00Z', venue: 'Estadio BBVA, Monterrey' },
  // MD2
  33: { kickoffUtc: '2026-06-20T17:00:00Z', venue: 'NRG Stadium, Houston' },
  34: { kickoffUtc: '2026-06-21T04:00:00Z', venue: 'Estadio BBVA, Monterrey' },
  // MD3
  35: { kickoffUtc: '2026-06-25T23:00:00Z', venue: 'Arrowhead Stadium, Kansas City' },
  36: { kickoffUtc: '2026-06-25T23:00:00Z', venue: 'AT&T Stadium, Dallas' },

  // ── Group G  [BEL, EGY, IRN, NZL] ────────────────────────────
  // MD1
  37: { kickoffUtc: '2026-06-15T19:00:00Z', venue: 'Lumen Field, Seattle' },
  38: { kickoffUtc: '2026-06-16T01:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  // MD2
  39: { kickoffUtc: '2026-06-21T19:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  40: { kickoffUtc: '2026-06-22T01:00:00Z', venue: 'BC Place, Vancouver' },
  // MD3
  41: { kickoffUtc: '2026-06-27T03:00:00Z', venue: 'BC Place, Vancouver' },
  42: { kickoffUtc: '2026-06-27T03:00:00Z', venue: 'Lumen Field, Seattle' },

  // ── Group H  [ESP, CPV, SAU, URY] ────────────────────────────
  // MD1
  43: { kickoffUtc: '2026-06-15T16:00:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },
  44: { kickoffUtc: '2026-06-15T22:00:00Z', venue: 'Hard Rock Stadium, Miami' },
  // MD2
  45: { kickoffUtc: '2026-06-21T16:00:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },
  46: { kickoffUtc: '2026-06-21T22:00:00Z', venue: 'Hard Rock Stadium, Miami' },
  // MD3
  47: { kickoffUtc: '2026-06-27T00:00:00Z', venue: 'Estadio Akron, Guadalajara' },
  48: { kickoffUtc: '2026-06-27T00:00:00Z', venue: 'NRG Stadium, Houston' },

  // ── Group I  [FRA, SEN, IRQ, NOR] ────────────────────────────
  // MD1
  49: { kickoffUtc: '2026-06-16T19:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
  50: { kickoffUtc: '2026-06-16T22:00:00Z', venue: 'Gillette Stadium, Foxborough' },
  // MD2
  51: { kickoffUtc: '2026-06-22T21:00:00Z', venue: 'Lincoln Financial Field, Philadelphia' },
  52: { kickoffUtc: '2026-06-23T00:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
  // MD3
  53: { kickoffUtc: '2026-06-26T19:00:00Z', venue: 'Gillette Stadium, Foxborough' },
  54: { kickoffUtc: '2026-06-26T19:00:00Z', venue: 'BMO Field, Toronto' },

  // ── Group J  [ARG, DZA, AUT, JOR] ────────────────────────────
  // MD1
  55: { kickoffUtc: '2026-06-17T01:00:00Z', venue: 'Arrowhead Stadium, Kansas City' },
  56: { kickoffUtc: '2026-06-17T04:00:00Z', venue: "Levi's Stadium, Santa Clara" },
  // MD2
  57: { kickoffUtc: '2026-06-22T17:00:00Z', venue: 'AT&T Stadium, Dallas' },
  58: { kickoffUtc: '2026-06-23T03:00:00Z', venue: "Levi's Stadium, Santa Clara" },
  // MD3
  59: { kickoffUtc: '2026-06-28T02:00:00Z', venue: 'AT&T Stadium, Dallas' },
  60: { kickoffUtc: '2026-06-28T02:00:00Z', venue: 'Arrowhead Stadium, Kansas City' },

  // ── Group K  [PRT, COD, UZB, COL] ────────────────────────────
  // MD1
  61: { kickoffUtc: '2026-06-17T17:00:00Z', venue: 'NRG Stadium, Houston' },
  62: { kickoffUtc: '2026-06-18T02:00:00Z', venue: 'Estadio Azteca, Mexico City' },
  // MD2
  63: { kickoffUtc: '2026-06-23T17:00:00Z', venue: 'NRG Stadium, Houston' },
  64: { kickoffUtc: '2026-06-24T02:00:00Z', venue: 'Estadio Akron, Guadalajara' },
  // MD3
  65: { kickoffUtc: '2026-06-27T23:30:00Z', venue: 'Hard Rock Stadium, Miami' },
  66: { kickoffUtc: '2026-06-27T23:30:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },

  // ── Group L  [ENG, HRV, GHA, PAN] ────────────────────────────
  // MD1
  67: { kickoffUtc: '2026-06-17T20:00:00Z', venue: 'AT&T Stadium, Dallas' },
  68: { kickoffUtc: '2026-06-17T23:00:00Z', venue: 'BMO Field, Toronto' },
  // MD2
  69: { kickoffUtc: '2026-06-23T20:00:00Z', venue: 'Gillette Stadium, Foxborough' },
  70: { kickoffUtc: '2026-06-23T23:00:00Z', venue: 'BMO Field, Toronto' },
  // MD3
  71: { kickoffUtc: '2026-06-27T21:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
  72: { kickoffUtc: '2026-06-27T21:00:00Z', venue: 'Lincoln Financial Field, Philadelphia' },

  // ── Round of 32 (matches 73-88) ───────────────────────────────
  73: { kickoffUtc: '2026-06-28T19:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  74: { kickoffUtc: '2026-06-29T20:30:00Z', venue: 'Gillette Stadium, Foxborough' },
  75: { kickoffUtc: '2026-06-30T01:00:00Z', venue: 'Estadio BBVA, Monterrey' },
  76: { kickoffUtc: '2026-06-29T17:00:00Z', venue: 'NRG Stadium, Houston' },
  77: { kickoffUtc: '2026-06-30T21:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
  78: { kickoffUtc: '2026-06-30T17:00:00Z', venue: 'AT&T Stadium, Dallas' },
  79: { kickoffUtc: '2026-07-01T01:00:00Z', venue: 'Estadio Azteca, Mexico City' },
  80: { kickoffUtc: '2026-07-01T16:00:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },
  81: { kickoffUtc: '2026-07-02T00:00:00Z', venue: "Levi's Stadium, Santa Clara" },
  82: { kickoffUtc: '2026-07-01T20:00:00Z', venue: 'Lumen Field, Seattle' },
  83: { kickoffUtc: '2026-07-02T23:00:00Z', venue: 'BMO Field, Toronto' },
  84: { kickoffUtc: '2026-07-02T19:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  85: { kickoffUtc: '2026-07-03T03:00:00Z', venue: 'BC Place, Vancouver' },
  86: { kickoffUtc: '2026-07-03T22:00:00Z', venue: 'Hard Rock Stadium, Miami' },
  87: { kickoffUtc: '2026-07-04T01:30:00Z', venue: 'Arrowhead Stadium, Kansas City' },
  88: { kickoffUtc: '2026-07-03T18:00:00Z', venue: 'AT&T Stadium, Dallas' },

  // ── Round of 16 (matches 89-96) ───────────────────────────────
  89: { kickoffUtc: '2026-07-04T21:00:00Z', venue: 'Lincoln Financial Field, Philadelphia' },
  90: { kickoffUtc: '2026-07-04T17:00:00Z', venue: 'NRG Stadium, Houston' },
  91: { kickoffUtc: '2026-07-05T20:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
  92: { kickoffUtc: '2026-07-06T00:00:00Z', venue: 'Estadio Azteca, Mexico City' },
  93: { kickoffUtc: '2026-07-06T19:00:00Z', venue: 'AT&T Stadium, Dallas' },
  94: { kickoffUtc: '2026-07-07T00:00:00Z', venue: 'Lumen Field, Seattle' },
  95: { kickoffUtc: '2026-07-07T16:00:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },
  96: { kickoffUtc: '2026-07-07T20:00:00Z', venue: 'BC Place, Vancouver' },

  // ── Quarter-finals (matches 97-100) ───────────────────────────
  97: { kickoffUtc: '2026-07-09T20:00:00Z', venue: 'Gillette Stadium, Foxborough' },
  98: { kickoffUtc: '2026-07-10T19:00:00Z', venue: 'SoFi Stadium, Los Angeles' },
  99: { kickoffUtc: '2026-07-11T21:00:00Z', venue: 'Hard Rock Stadium, Miami' },
  100: { kickoffUtc: '2026-07-12T01:00:00Z', venue: 'Arrowhead Stadium, Kansas City' },

  // ── Semi-finals (matches 101-102) ─────────────────────────────
  101: { kickoffUtc: '2026-07-14T19:00:00Z', venue: 'AT&T Stadium, Dallas' },
  102: { kickoffUtc: '2026-07-15T19:00:00Z', venue: 'Mercedes-Benz Stadium, Atlanta' },

  // ── Third-place match (match 103) ─────────────────────────────
  103: { kickoffUtc: '2026-07-18T21:00:00Z', venue: 'Hard Rock Stadium, Miami' },

  // ── Final (match 104) ─────────────────────────────────────────
  104: { kickoffUtc: '2026-07-19T19:00:00Z', venue: 'MetLife Stadium, East Rutherford' },
}

/** Returns the kickoff time for a match, or null if not found. */
export function getMatchKickoff(matchId: number): Date | null {
  const entry = schedule[matchId]
  return entry ? new Date(entry.kickoffUtc) : null
}

/** Returns the venue for a match, or null if not found. */
export function getMatchVenue(matchId: number): string | null {
  return schedule[matchId]?.venue ?? null
}

/**
 * Deadline for a result-entry batch (RoundKey).
 * = earliest kickoff among all matches in that round.
 */
export function getRoundDeadline(roundKey: RoundKey): Date {
  const matchIds = getMatchIdsForRound(roundKey)
  let earliest = Infinity
  for (const id of matchIds) {
    const entry = schedule[id]
    if (entry) {
      const t = new Date(entry.kickoffUtc).getTime()
      if (t < earliest) earliest = t
    }
  }
  return new Date(earliest)
}

/**
 * Deadline for a prediction round (PredictionRoundKey).
 * = earliest kickoff among all matches in that prediction round.
 * Champion pick shares the 'group' deadline.
 */
export function getPredictionRoundDeadline(roundKey: PredictionRoundKey): Date {
  const [min, max] = PREDICTION_ROUND_RANGES[roundKey]
  let earliest = Infinity
  for (let id = min; id <= max; id++) {
    const entry = schedule[id]
    if (entry) {
      const t = new Date(entry.kickoffUtc).getTime()
      if (t < earliest) earliest = t
    }
  }
  return new Date(earliest)
}

/**
 * Whether now is past the deadline for a prediction round.
 * Used for both server enforcement and UI effective-status derivation.
 */
export function isDeadlinePassed(roundKey: PredictionRoundKey, now: Date = new Date()): boolean {
  const deadline = getPredictionRoundDeadline(roundKey)
  return now.getTime() >= deadline.getTime()
}

/** Feature flag: set NEXT_PUBLIC_ENABLE_DEADLINES=true in .env.local to activate. */
export const DEADLINE_ENFORCEMENT_ENABLED =
  typeof process !== 'undefined' &&
  process.env?.NEXT_PUBLIC_ENABLE_DEADLINES === 'true'
